
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
name: GenerateSnake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  update-repository:
    name: MrSampaio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Snake
        uses: Platane/snk@v2
        id: snake-svg
        with:
          github_user_name: ${{ github.MrSampaio }}
          outputs: |
            ./img/snake.svg
            ./img/snake_dark.svg?palette=github-dark
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: 'GitHub Actions'
          author_email: 'action@github.com'
          message: ':rocket: Update snake'
